# Generated by Django 3.0 on 2019-12-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ('-created_at', '-updated_at')},
        ),
    ]
