# Generated by Django 3.0 on 2019-12-13 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0002_auto_20191214_0041'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('width', models.FloatField()),
                ('width_unit', models.CharField(choices=[('cm', 'centimeters'), ('m', 'meters'), ('in', 'inches')], default='in', max_length=2)),
                ('weight', models.FloatField()),
                ('weight_unit', models.CharField(choices=[('Kg', 'kilogram'), ('t', 'metric ton')], default='Kg', max_length=2)),
                ('stock_timestamp', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
                ('stocked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
