# Generated by Django 3.0 on 2019-12-13 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributor', '0001_initial'),
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('width_unit', models.CharField(choices=[('cm', 'centimeters'), ('m', 'meters'), ('in', 'inches')], default='in', max_length=2)),
                ('height', models.FloatField()),
                ('height_unit', models.CharField(choices=[('cm', 'centimeters'), ('m', 'meters'), ('in', 'inches')], default='in', max_length=2)),
                ('weight', models.FloatField()),
                ('weight_unit', models.CharField(choices=[('Kg', 'kilogram'), ('t', 'metric ton')], default='Kg', max_length=2)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Roll')),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('weight_unit', models.CharField(choices=[('Kg', 'kilogram'), ('t', 'metric ton')], default='Kg', max_length=2)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Bag')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Roll')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assingment_timestamp', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Bag')),
                ('distrubutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.Distributor')),
            ],
        ),
    ]
