# Generated by Django 3.0 on 2019-12-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_bag_ship_waste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='distrubutor',
            new_name='distributor',
        ),
    ]
