# Generated by Django 3.0 on 2019-12-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_auto_20191214_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='status',
            field=models.CharField(choices=[('STOCKED', 'In Stock'), ('SHIPPED', 'Shipped')], default='STOCKED', max_length=10),
        ),
    ]
