# Generated by Django 3.0 on 2019-12-14 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_auto_20191215_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
