# Generated by Django 3.0 on 2019-12-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20191214_0041'),
        ('distributor', '0001_initial'),
        ('factory', '0006_waste_create_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trxn_type', models.IntegerField()),
                ('trxn_timestamp', models.DateTimeField(auto_now_add=True)),
                ('bag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.Bag')),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor.Distributor')),
                ('roll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.Roll')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
                ('ship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.Ship')),
                ('waste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.Waste')),
            ],
        ),
    ]
