# Generated by Django 3.0 on 2019-12-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_inventorytransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransactions',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
