# Generated by Django 3.0 on 2019-12-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_inventorytransactions_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransactions',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='inventorytransactions',
            name='seller',
        ),
    ]
