# Generated by Django 3.0 on 2019-12-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_auto_20191216_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='stocked_by',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='weight_unit',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='width_unit',
        ),
    ]
