# Generated by Django 3.0 on 2019-12-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_auto_20191217_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='gsm',
            field=models.IntegerField(),
        ),
    ]
