# Generated by Django 3.0 on 2019-12-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0012_inventorytransactions_trxn_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
