# Generated by Django 3.0 on 2019-12-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0013_roll_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='roll_type',
            field=models.CharField(choices=[('d', 'd-type rolls'), ('u', 'u-type rolls')], default='d', max_length=2),
        ),
    ]
