# Generated by Django 3.0 on 2019-12-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0014_roll_roll_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='height',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='height_unit',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='weight_unit',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='width',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='width_unit',
        ),
        migrations.RemoveField(
            model_name='waste',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='waste',
            name='weight_unit',
        ),
        migrations.AddField(
            model_name='bag',
            name='unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorytransactions',
            name='unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
