# Generated by Django 3.0 on 2019-12-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0015_auto_20191217_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransactions',
            name='unit',
            field=models.IntegerField(null=True),
        ),
    ]
