# Generated by Django 3.0 on 2020-01-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0017_remove_roll_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='length',
            field=models.FloatField(null=True),
        ),
    ]
