# Generated by Django 3.0 on 2020-01-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0019_auto_20200105_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bag',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
