# Generated by Django 3.0 on 2020-01-05 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factory', '0020_auto_20200105_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('pricing', models.CharField(choices=[('basic', 'Basic'), ('colour', 'Colour')], default='basic', max_length=10)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('bag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.Bag')),
                ('cart_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
