# Generated by Django 3.0 on 2020-01-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0021_shipcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipcart',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
