# Generated by Django 3.0 on 2020-01-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0024_packingslips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='distributor',
        ),
        migrations.AddField(
            model_name='ship',
            name='package',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='factory.PackingSlips'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='pricing',
            field=models.CharField(choices=[('basic', 'Basic'), ('colour', 'Colour')], default='basic', max_length=10),
        ),
        migrations.AddField(
            model_name='ship',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
