# Generated by Django 3.0 on 2020-01-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0025_auto_20200107_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='print_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Flexo', 'Flexo')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='bag',
            name='bag_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Offset', 'Offset')], default='Normal', max_length=10),
        ),
    ]
