# Generated by Django 3.0 on 2020-01-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0026_auto_20200112_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='print_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Offset', 'Offset')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='bag',
            name='bag_type',
            field=models.CharField(choices=[('d-cut', 'd-cut'), ('u-cut', 'u-cut'), ('handle', 'handle')], default='d-cut', max_length=10),
        ),
    ]
