# Generated by Django 3.0 on 2020-01-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20191214_0041'),
        ('factory', '0027_auto_20200112_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
    ]
