# Generated by Django 3.0 on 2020-01-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0029_auto_20200113_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingslips',
            name='wcut_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='bndl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='pricing',
            field=models.CharField(choices=[('basic', 'Basic'), ('colour', 'Colour'), ('w-cut', 'W-CUT')], default='basic', max_length=10),
        ),
    ]
