# Generated by Django 3.0 on 2020-01-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0030_auto_20200113_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='remarks',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='shipcart',
            name='remarks',
            field=models.CharField(default='', max_length=30),
        ),
    ]
