# Generated by Django 3.0 on 2020-01-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0032_auto_20200113_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingslips',
            name='advance_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='basic_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='basic_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='basic_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='block_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='block_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='block_unit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='color_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='color_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='color_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='fare_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='print_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='print_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='print_unit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='wcut_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='wcut_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packingslips',
            name='wcut_weight',
            field=models.FloatField(null=True),
        ),
    ]
